---
default:
    - debug: true
      open: public/index-debug.html
      extras: -use-network=false -static-link-runtime-shared-libraries
    
library-path:
    - source/swc

source-path:
    - source/libs
    - source/classes
    
applications:
    - class: source/classes/simplesite_loader.as
      output: public/simplesite_loader.swf
    - class: source/classes/simplesite_main.as
      output: public/simplesite_main.swf
    - class: source/classes/simplesite/views/AlbumView.as
      output: public/AlbumView.swf
    - class: source/classes/simplesite/views/WebCamView.as
      output: public/WebCamView.swf
    - class: source/classes/simplesite/views/HomeView.as
      output: public/HomeView.swf
      # exclude: source/classes/Other.as
# asdoc:
#     title: "My ActionScript project"
#     footer: "My ActionScript project footer"
#     output: docs/
#     exclude-dirs: 
#       - source/classes/com/greensock/
#       - source/classes/br/com/stimuli/
